-- Real file attachments for tasks: metadata table + a private Storage bucket.
-- Storage path convention: "{project_id}/{task_id}/{timestamp}-{filename}",
-- which lets the storage.objects policies below reuse the existing
-- projects/workspace visibility rules with a single lookup on `projects`.

create table if not exists public.task_attachments (
  id uuid primary key default gen_random_uuid(),
  task_id text not null references public.tasks(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  content_type text,
  size_bytes integer not null default 0 check (size_bytes >= 0),
  uploaded_by text references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists task_attachments_task_idx on public.task_attachments(task_id);

alter table public.task_attachments enable row level security;

revoke all on public.task_attachments from anon, authenticated;
grant select on public.task_attachments to anon;
grant select, insert, update, delete on public.task_attachments to authenticated;

create policy "Visible attachments are readable" on public.task_attachments for select
  using (exists (
    select 1 from public.tasks t
    join public.board_columns c on c.id = t.column_id
    join public.projects p on p.id = c.project_id
    where t.id = task_id and (p.visibility = 'public' or public.is_workspace_member(p.workspace_id))
  ));

create policy "Members manage attachments" on public.task_attachments for all to authenticated
  using (exists (
    select 1 from public.tasks t
    join public.board_columns c on c.id = t.column_id
    join public.projects p on p.id = c.project_id
    where t.id = task_id and public.is_workspace_member(p.workspace_id)
  ))
  with check (exists (
    select 1 from public.tasks t
    join public.board_columns c on c.id = t.column_id
    join public.projects p on p.id = c.project_id
    where t.id = task_id and public.is_workspace_member(p.workspace_id)
  ));

-- Private bucket: reads go through short-lived signed URLs generated by the
-- app server (see SupabaseProjectRepository), never a public URL.
insert into storage.buckets (id, name, public, file_size_limit)
values ('task-attachments', 'task-attachments', false, 26214400) -- 25 MiB
on conflict (id) do nothing;

create policy "Read attachments of visible projects" on storage.objects for select
  using (
    bucket_id = 'task-attachments'
    and exists (
      select 1 from public.projects p
      where p.id = (storage.foldername(name))[1]
        and (p.visibility = 'public' or public.is_workspace_member(p.workspace_id))
    )
  );

create policy "Members upload attachments" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'task-attachments'
    and exists (
      select 1 from public.projects p
      where p.id = (storage.foldername(name))[1]
        and public.is_workspace_member(p.workspace_id)
    )
  );

create policy "Members delete attachments" on storage.objects for delete to authenticated
  using (
    bucket_id = 'task-attachments'
    and exists (
      select 1 from public.projects p
      where p.id = (storage.foldername(name))[1]
        and public.is_workspace_member(p.workspace_id)
    )
  );

-- `save_project_state` used to delete every column/task for the project and
-- reinsert them from scratch on EVERY board save. That's fine for columns and
-- tasks themselves, but it means any child row referencing a task by FK (like
-- task_attachments, on delete cascade) would get silently wiped out the next
-- time the user edited anything on the board at all, not just that task.
-- Switched to a diff: delete only the columns/tasks no longer present in the
-- payload, upsert the rest in place so their identity (and children) survive.
create or replace function public.save_project_state(p_project jsonb)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  project_workspace_id text;
  incoming_column_ids text[];
  incoming_task_ids text[];
  column_item record;
  task_item record;
begin
  select workspace_id into project_workspace_id from public.projects where id = p_project->>'id';
  if project_workspace_id is null or not public.is_workspace_member(project_workspace_id) then
    raise exception 'Not authorized to update this project';
  end if;

  update public.projects set
    name = p_project->>'name',
    subtitle = coalesce(p_project->>'subtitle', ''),
    visibility = coalesce(p_project->>'visibility', 'private'),
    updated_at = now()
  where id = p_project->>'id';

  select array(select value->>'id' from jsonb_array_elements(p_project->'columns'))
    into incoming_column_ids;

  select array(
    select t.value->>'id'
    from jsonb_array_elements(p_project->'columns') as c(value)
    cross join lateral jsonb_array_elements(c.value->'tasks') as t(value)
  ) into incoming_task_ids;

  delete from public.tasks
  where column_id in (select id from public.board_columns where project_id = p_project->>'id')
    and not (id = any(coalesce(incoming_task_ids, array[]::text[])));

  delete from public.board_columns
  where project_id = p_project->>'id'
    and not (id = any(coalesce(incoming_column_ids, array[]::text[])));

  for column_item in select value, ordinality from jsonb_array_elements(p_project->'columns') with ordinality loop
    insert into public.board_columns (id, project_id, name, position)
    values (column_item.value->>'id', p_project->>'id', column_item.value->>'name', column_item.ordinality - 1)
    on conflict (id) do update set
      project_id = excluded.project_id,
      name = excluded.name,
      position = excluded.position;

    for task_item in select value, ordinality from jsonb_array_elements(column_item.value->'tasks') with ordinality loop
      insert into public.tasks (id, column_id, title, description, priority, assignee_id, due_date, files_count, tags, highlighted, position)
      values (
        task_item.value->>'id',
        column_item.value->>'id',
        task_item.value->>'title',
        coalesce(task_item.value->>'description', ''),
        coalesce(task_item.value->>'priority', 'medium'),
        nullif(task_item.value->'assignee'->>'id', ''),
        coalesce(nullif(task_item.value->>'dueDate', '')::date, current_date),
        coalesce((task_item.value->>'filesCount')::integer, 0),
        array(select jsonb_array_elements_text(coalesce(task_item.value->'tags', '[]'::jsonb))),
        coalesce((task_item.value->>'highlighted')::boolean, false),
        task_item.ordinality - 1
      )
      on conflict (id) do update set
        column_id = excluded.column_id,
        title = excluded.title,
        description = excluded.description,
        priority = excluded.priority,
        assignee_id = excluded.assignee_id,
        due_date = excluded.due_date,
        files_count = excluded.files_count,
        tags = excluded.tags,
        highlighted = excluded.highlighted,
        position = excluded.position,
        updated_at = now();
    end loop;
  end loop;
end;
$$;

grant execute on function public.save_project_state(jsonb) to authenticated;
